m_mat = StandardMaterial('test', ShadingModel.MetalRough)
m_mat.baseColor = float4(1, 1, 1, 1)
mesh = TriangleMesh()
print("[MESH-SMOKE] mesh =", mesh)
mesh.addVertex(float3(0, 0, 0), float3(0, 1, 0), float2(0, 0))
mesh.addVertex(float3(1, 0, 0), float3(0, 1, 0), float2(1, 0))
mesh.addVertex(float3(0, 0, 1), float3(0, 1, 0), float2(0, 1))
mesh.addTriangle(0, 1, 2)
print("[MESH-SMOKE] verts =", len(mesh.vertices))
mid = sceneBuilder.addTriangleMesh(mesh, m_mat)
print("[MESH-SMOKE] mid =", mid)
exit()
